PREFIX : <http://www.miamidade.gov/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?table ?column
WHERE {
  ?table a :DBTable .
  ?column :hasTable ?table .
  ?column a :DBColumn .
}