-- Ordered Delete of all rows in DB
delete CIRM_SRREQ_SRACTOR;
delete CIRM_SR_ACTOR;
delete CIRM_SR_ACTIVITY;
delete CIRM_SR_REQUESTS;
delete CIRM_MDC_ADDRESS;

delete CIRM_SERVICE_ACTION;
delete CIRM_SERVICE_CALL;

delete CIRM_OWL_OBJECT_PROPERTY;
delete CIRM_CLASSIFICATION;
delete CIRM_OWL_DATA_PROPERTY;
delete CIRM_OWL_DATA_VAL_CLOB;
delete CIRM_OWL_DATA_VAL_DATE;
delete CIRM_OWL_DATA_VAL_DOUBLE;
delete CIRM_OWL_DATA_VAL_INTEGER;
delete CIRM_OWL_DATA_VAL_STRING;

delete CIRM_IRI;
delete CIRM_IRI_TYPE;

drop sequence CIRM_SEQUENCE;
create sequence CIRM_SEQUENCE;