--A) INTIALIZE CIRM_IRI_TYPE TABLE
INSERT INTO CIRM_IRI_TYPE (ID,IRI) VALUES (1,'Class');
INSERT INTO CIRM_IRI_TYPE (ID,IRI) VALUES (2,'DataProperty');
INSERT INTO CIRM_IRI_TYPE (ID,IRI) VALUES (3,'Datatype');
INSERT INTO CIRM_IRI_TYPE (ID,IRI) VALUES (4,'NamedIndividual');
INSERT INTO CIRM_IRI_TYPE (ID,IRI) VALUES (5,'ObjectProperty');
INSERT INTO CIRM_IRI_TYPE (ID,IRI) VALUES (6,'AnnotationProperty');