CREATE OR REPLACE VIEW CIRMDW_ALL_PROPERTY_VALUE_VIEW AS
SELECT
DP.SUBJECT AS SUBJECT_ID,
DP.PREDICATE AS PREDICATE_ID,
NULL AS OBJECT_ID,
VDAT.VALUE_DATE,
VD.VALUE_DOUBLE,
VI.VALUE_INTEGER,
VS.VALUE_VARCHAR
FROM CIRM_OWL_DATA_PROPERTY DP LEFT OUTER
JOIN CIRM_OWL_DATA_VAL_DATE VDAT ON (DP.VALUE_ID = VDAT.ID) LEFT OUTER
JOIN CIRM_OWL_DATA_VAL_DOUBLE VD ON (DP.VALUE_ID = VD.ID) LEFT OUTER
JOIN CIRM_OWL_DATA_VAL_INTEGER VI ON (DP.VALUE_ID = VI.ID) LEFT OUTER
JOIN CIRM_OWL_DATA_VAL_STRING VS ON (DP.VALUE_ID = VS.ID)
WHERE DP.TO_DATE is null
UNION
ALL
SELECT
OP.SUBJECT AS SUBJECT_ID,
OP.PREDICATE AS PREDICATE_ID,
OP.OBJECT AS OBJECT_ID,
NULL,
NULL,
NULL,
NULL
FROM CIRM_OWL_OBJECT_PROPERTY OP
WHERE OP.TO_DATE is null

---

CREATE OR REPLACE VIEW CIRMDW_OBJECT_PROPERTY_VIEW AS
SELECT
A.ID AS P_ID,
REPLACE(A.IRI, 'http://www.miamidade.gov/cirm/legacy#','') AS PREDICATE,
A.IRI_TYPE_ID AS PREDICATE_TYPE,
C.ID AS S_ID,
REPLACE(C.IRI, 'http://www.miamidade.gov/cirm/legacy#','') AS SUBJECT,
C.IRI_TYPE_ID AS SUBJECT_IRI_TYPE,
D.ID AS O_ID,
REPLACE(D.IRI, 'http://www.miamidade.gov/cirm/legacy#','') AS OBJECT,
D.IRI_TYPE_ID AS OBJECT_IRI_TYPE
FROM CIRM_IRI A, CIRM_OWL_OBJECT_PROPERTY B, CIRM_IRI C, CIRM_IRI D
WHERE A.ID = B.PREDICATE
AND B.SUBJECT = C.ID
AND B.OBJECT = D.ID
AND B.TO_DATE IS NULL
ORDER BY S_ID


--
--DROP INDEX CIRMDWSCHM.CIRMDW_IDX_APV_SUBJECT_ID;

--DROP MATERIALIZED VIEW CIRMDWSCHM.CIRMDW_ALL_PROPERTY_VIEW;

CREATE MATERIALIZED VIEW CIRMDWSCHM.CIRMDW_ALL_PROPERTY_VIEW AS
SELECT
PVV.SUBJECT_ID,
PVV.PREDICATE_ID,
REPLACE(IP.IRI, 'http://www.miamidade.gov/cirm/legacy#', '') AS PREDICATE_IRI,
IP.IRI_LABEL AS PREDICATE_LABEL,
PVV.OBJECT_ID,
COALESCE(IO.IRI_LABEL, SUBSTR(IO.IRI, INSTR(IO.IRI, '#') + 1) ) AS OBJECT_LABEL, --PERMANENT FIX
PVV.VALUE_DATE,
PVV.VALUE_DOUBLE,
PVV.VALUE_INTEGER,
PVV.VALUE_VARCHAR
FROM CIRMDW_ALL_PROPERTY_VALUE_VIEW PVV LEFT OUTER
JOIN CIRM_IRI IP ON (PVV.PREDICATE_ID = IP.ID) LEFT OUTER
JOIN CIRM_IRI IO ON (PVV.OBJECT_ID = IO.ID)

/** Create index **/
CREATE INDEX CIRMDW_IDX_APV_SUBJECT_ID ON CIRMDWSCHM.CIRMDW_ALL_PROPERTY_VIEW (SUBJECT_ID)